# https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/
groups:
- name: example
  labels:
    team: myteam
  rules:
  - alert: HighRequestLatency
    expr: job:request_latency_seconds:mean5m{job="myjob"} > 0.5
    for: 10m
    keep_firing_for: 5m
    labels:
      severity: page
    annotations:
      summary: High request latency

  - alert: APIHighRequestLatency
    expr: api_http_request_latencies_second{quantile="0.5"} > 1
    for: 10m
    annotations:
      summary: "High request latency on {{ $labels.instance }}"
      description: "{{ $labels.instance }} has a median request latency above 1s (current value: {{ $value }}s)"
    
  - alert: NodeExporterDown
    expr: up{job="node-exporter"} == 0
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "Node Exporter is down"