# deploy/elk/setup-kibana/Dockerfile.setup-kibana
FROM alpine:3.20

RUN apk add --no-cache curl ca-certificates

WORKDIR /work

COPY dashboard.ndjson /work/dashboard.ndjson
COPY setup-kibana.sh /usr/local/bin/setup-kibana.sh
RUN chmod +x /usr/local/bin/setup-kibana.sh

ENTRYPOINT ["/usr/local/bin/setup-kibana.sh"]
