server.name: kibana
server.host: 0.0.0.0
server.publicBaseUrl: https://localhost:5601

# Kibana TLS
server.ssl.enabled: true
server.ssl.certificate: config/certs/kibana/kibana.crt
server.ssl.key: config/certs/kibana/kibana.key
xpack.security.secureCookies: true

# Elasticsearch Connection
elasticsearch.hosts: ["https://es01:9200"]
elasticsearch.username: kibana_system
elasticsearch.password: ${ELASTICSEARCH_PASSWORD}
elasticsearch.ssl.certificateAuthorities: ["config/certs/ca/ca.crt"]

# Encryption
xpack.security.encryptionKey: ${KBN_SECURITY_KEY}
xpack.encryptedSavedObjects.encryptionKey: ${KBN_ENCRYPTED_SAVED_OBJECTS_KEY}
xpack.reporting.encryptionKey: ${KBN_REPORTING_KEY}

# Other
server.shutdownTimeout: "5s"
monitoring.ui.container.elasticsearch.enabled: true
telemetry.enabled: false
xpack.fleet.enabled: false
# xpack.securitySolution.telemetry.enabled: false