FROM nginx:1.29 AS production

RUN set -x \
  && rm -f /etc/nginx/conf.d/default.conf

RUN rm -f /var/log/nginx/access.log /var/log/nginx/error.log \
 && touch /var/log/nginx/access.log /var/log/nginx/error.log \
 && chown -R nginx:nginx /var/log/nginx

COPY deploy/nginx/nginx.conf /etc/nginx/nginx.conf
COPY deploy/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY deploy/nginx/metrics.conf /etc/nginx/metrics.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
