global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
- "alertmanager_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - prometheus:9090
  - job_name: 'node-exporter'
    static_configs:
      - targets:
        - node-exporter:9100
  - job_name: 'fastify-app'
    static_configs:
      - targets: ['app:9464']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']