ARG STACK_VERSION=9.1.5
FROM docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}

USER root

COPY setup-certs.sh /usr/local/bin/setup-certs.sh
RUN chmod +x /usr/local/bin/setup-certs.sh

ENTRYPOINT ["/usr/local/bin/setup-certs.sh"]
